### ISSUE TITLE
implement 5 tests for the Bunch Transport tab

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#103]

**Comment by MZHarrison** [comment]
All of the non-GUI Bunch Transport code for Elegant and the home-grown Laser Transport code is tested by:
 - radtrack/tests/elegant/expandCollapseBeamline_test.py
 - radtrack/tests/elegant/importExport_test.py

Peripheral functions are tested by:
 - radtrack/tests/util/insideQuote_test.py
 - radtrack/tests/util/rpn_test.py
 - radtrack/tests/util/stripComments_test.py
 - radtrack/tests/util/unitConversion_test.py

The Genesis Transport tab can't be tested until the import/export functions are written. (Issue #109)
