### ISSUE TITLE
in Data Viz tab, allow user to specify line types, marker types, etc.

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#107]
related issues:
   specify mins and maxes
   force same vertical mins and maxes when y0 and y1 are both plotted

**Comment by qedseung** [comment]
This will be related to the overall overhaul of data viz

**Comment by MZHarrison** [comment]
This is already possible by clicking the green check mark above the plots. We may still want to improve the dialogs somehow.
