### ISSUE TITLE
Insert interface into or emulate QFileDialog

### ISSUE THREAD

**Issue by robnagler** [radiasoft/radtrack#11]
QFileDialog file browser needs an interface so that calls to the operating system (directory listings and such) go through an abstraction instead of directly to the file system. This might be done with dependency injection (DI).

An alternative is to rewrite the file browser so that an file system abstraction can be inserted.

**Comment by bruhwile** [comment]
Can this issue be closed?

**Comment by MZHarrison** [comment]
I'm curious what problem this issue is meant to address.

**Comment by robnagler** [comment]
I think this was mean to address the problem with splitting out the
interface so we could use a network connection between the GUI and the
backend. I don't think we are solving that problem any more so I guess this
can be closed.
