### ISSUE TITLE
python setup.py develop no longer works

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#110]
$ python setup.py develop
    error in radtrack setup command: package_data must be a dictionary
    mapping package names to lists of wildcard patterns

**Comment by robnagler** [comment]
Sorry about that. I have been working on this. I will get it fixed tomorrow.

Rob

**Comment by robnagler** [comment]
This should be fixed. Checkout radtrack and pykern. Let me know

**Comment by bruhwile** [comment]
Works for me.

**Comment by MZHarrison** [comment]
Now I'm getting a different error after pulling the latest from pykern and radtrack. After running `python setup.py develop` in the pykern directory (which succeeds), running `python setup.py develop` in the radtrack directory results in:

    Searching for pykern>=20150510.0 
    Reading https://pypi.python.org/simple/pykern/
    Couldn't retrieve index page for 'pykern'
    Scanning index of all packages (this may take a while)
    Reading https://pypi.python.org/simple/
    No local packages or download links found for pykern>=20150510.0
    error: Could not find suitable distribution for Requirement.parse('pykern>=20150510.0')

Full output here: https://gist.github.com/MZHarrison/7a818638ec0b4f49ca20

**Comment by robnagler** [comment]
I'll check it out later today. One thing to try is to change the pykern
install to a "python setup.py install" to see if that makes a difference.

Rob

**Comment by bruhwile** [comment]
For me, on linux, 'python setup.py develop' is working in pykern/ and in
radtrack/

Mark -- are you seeing this error on Windows?

David

**Comment by MZHarrison** [comment]
Yes, this error is in Windows.

**Comment by robnagler** [comment]
How about

cd pykern
pip uninstall -y pykern
python setup.py develop

Rob

**Comment by MZHarrison** [comment]
I ended up deleting both the radtrack and pykern repositories on my computer and recloning them. `python setup.py develop` worked in both cases. Looks like there was some leftover files from previous runs that were interfering.
