### ISSUE TITLE
python setup.py develop installs Unix/Mac versions of pytest on Windows

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#111]
After running `python setup.py develop` for both pykern and radtrack, attempting to run `python setup.py test` results in `INTERNALERROR` messages from pytest, (copied here: https://gist.github.com/MZHarrison/347a5b284baf190e0041). The last part is:

    C:\Users\Mark Harrison\Documents\GitHub\pykern>python setup.py test
    ...
    INTERNALERROR>   File "C:\Users\Mark Harrison\Anaconda\lib\site-packages\py\_process\forkedfunc.py", line 45, in __init__
    INTERNALERROR>     pid = os.fork()
    INTERNALERROR> AttributeError: 'module' object has no attribute 'fork'

    ==============================  in 0.41 seconds ===============================
    Exception AttributeError: "ForkedFunc instance has no attribute 'pid'" in <bound method ForkedFunc.__del__ of <py._process.forkedfunc.ForkedFunc instance at 0x0324A670>> ignored

`os.fork()` is only available on Unix (and presumably Mac) systems.

**Comment by robnagler** [comment]
pytest's xdist plugin doesn't have a feature test for this. I added one to
pykern.py that checks for the existence of os.fork and then doesn't pass
--boxed.

Pull pykern . I don't think you should have to install again if you are in
develop mode.

Rob

**Comment by MZHarrison** [comment]
Issue has been fixed.
