### ISSUE TITLE
install Genesis in RadiaSoft container

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#118]
Let David know if you need more detailed build instructions.

**Comment by bruhwile** [comment]
Genesis build sequence:
> wget http://genesis.web.psi.ch/Genesis-Beta/genesis-3.2.1-beta.tar.gz
> gunzip genesis-3.2.1-beta.tar.gz
> tar -xvf genesis-3.2.1-beta.tar
> cd Develop/source
***
In this directory, change these two lines:
LIB= -lmpi_cxx -lgfortran
CCOMPILER = h5pcc

to the following:
LIB= -lgfortran -lstdc++ -lhdf5 -L/usr/lib64 -L/usr/lib64/openmpi/lib
CCOMPILER = mpicxx
***
> rm ../bin/genesis
> make
> ls -ld genesis
-rwxrwx--- 1 vagrant vagrant 262921 Sep  3 17:05 genesis

**Comment by MZHarrison** [comment]
Given Rob's comment here (https://github.com/radiasoft/radtrack/issues/145#issuecomment-192089272), I'm closing this.
