### ISSUE TITLE
rt_popup

### ISSUE THREAD

**Issue by qedseung** [radiasoft/radtrack#122]
rt_popup doesn't accept py_type as string

File "/home/vagrant/src/radiasoft/radtrack/radtrack/rt_popup.py", line 41, in get_widget_value
    raise AssertionError('bad type: ' + str(decl.py_type))
AssertionError: bad type: <type 'str'>

**Comment by robnagler** [comment]
You can extend get_widget_value to understand other types, e.g. str. Be
careful to use pkcompat.isinstance_str or something similar so it's
forwards compatible with Py3.

Rob
