### ISSUE TITLE
2 Enumerated Type Get Overwritten

### ISSUE THREAD

**Issue by qedseung** [radiasoft/radtrack#124]
2 enumerated types get overwritten and turned into NoneType after clicking ok in the io_control and particle_loading dialog boxes.
The parameters are FFSpectrum and GenerateGaus.
![screen shot 2015-10-13 at 4 06 20 pm](https://cloud.githubusercontent.com/assets/10424478/10470770/77bbe006-71c4-11e5-8bc2-ec365bd151af.png)

**Comment by robnagler** [comment]
Enum member names are `name` not `display_name` so the enum member was not being found, and the loop in get_widget_value was not checking that the enum value was not being found so the value was None. The right way to look up enum values to convert from the widget is to index the `list()` that is returned by the type. This is the inverse of using the `index()` to look up the index of the enum from the `list()` in set_widget_value. Fixed 4070196
