### ISSUE TITLE
needed: rotation and window resizing feature in bunch transport window

### ISSUE THREAD

**Issue by andonian** [radiasoft/radtrack#127]
Bunch transport window:
When opening long beam lines, that have a bend at the very beginning, the display shows the beam line from a top down view at an angle which makes it difficult to see whats going on, even when zoomed in.
We need to have a rotation feature (e.g. subtle half circle with arrow at bottom right corner) for such cases.
Also, we need a  window resizing feature in the same visualization so user can alternate b/w detailed views of beam line, and spreadsheet of elements on the fly.

<img width="1277" alt="screen shot 2015-11-11 at 4 06 33 pm" src="https://cloud.githubusercontent.com/assets/10441770/11107029/b2e2a86e-888e-11e5-8a45-3f200f4b8d91.png">

**Comment by MZHarrison** [comment]
Rotation issue resolved by commit 8fc1d74a8ff462b80eec4415b358f3ec66a2c13c. Implemented by context menu when right-clicking image.

**Comment by MZHarrison** [comment]
Not done yet: need window resizing.
