### ISSUE TITLE
ProjectFile store/retrieve

### ISSUE THREAD

**Issue by robnagler** [radiasoft/radtrack#13]
RbGlobal manages the files associated with projects. The abstraction here would be a bit different than other file opens, and possibly could be related. 

It's probably best for the ProjectFile abstraction to be "opinionated" about locations and naming. Will have to study how people use RadTrack, but would probably want a flat list of projects to choose from with, possibly, a versioning system to allow users to see a project's history.

Research topic.

**Comment by MZHarrison** [comment]
Documenting some ideas for how RadTrack handles projects. Please comment.

- Upon starting, RadTrack creates a session directory named in a dated format (YYYY-MM-DD-HH-MM-SS) in a hidden directory in the user's personal folder (~/.radtrack/ in Linux, %HOMEPATH%/RadTrack/ in Windows with hidden attribute set, etc.).
- All implicitly generated files generated files (not created by File->Export current tab...) are kept in the session directory.
- When a user quits RadTrack, the information in all open tabs is saved to the session directory. The user is presented with an option to save the project. If the user chooses to save, the session directory is moved and renamed according to the user's choices. If the user does not save, nothing happens. The session directory is left in place.
- The user will have the ability to load both explicitly saved projects and choose from a list of recent unsaved projects by date.

**Comment by bruhwile** [comment]
This sounds very good to me.

David

**Comment by robnagler** [comment]
I like the workflow. Saving everything will help the user feel comfortable
with the product. I do have a few suggestions.


>    - Upon starting, RadTrack creates a session directory named in a dated
>    format (YYYY-MM-DD-HH-MM-SS) in a hidden directory in the user's personal
>    folder (~/.radtrack/ in Linux, %HOMEPATH%/RadTrack/ in Windows with hidden
>    attribute set, etc.).
>
> I think having ~/RadTrack that holds all the files is great. Organizing
that by date/time is good, too. I think we should avoid hiding files. One
of the problems many users have is "where did it go?"


>    - All implicitly generated files generated files (not created by
>    File->Export current tab...) are kept in the session directory.
>
> One thing we should do is use a practical syntax for our own files, e.g.
YAML, which people can view/edit if they need/want to. Obviously, any other
3rd party format files would be stored in the appropriate syntax. I would
suggest that we structure the naming of tabs to be the same as the files
that are written, that is, if the tab is BunchTransport, the files
generated would be BunchTransport.*. I also recommend we limit putting
spaces in tabs. Many of our users are familiar with the command line, and
spaces in filenames makes things more difficult to manipulate on the
command line.



>    - When a user quits RadTrack, the information in all open tabs is
>    saved to the session directory. The user is presented with an option to
>    save the project. If the user chooses to save, the session directory is
>    moved and renamed according to the user's choices. If the user does not
>    save, nothing happens. The session directory is left in place.
>
>  If we name all the files by date (possibly shorter 20150322-101010) lets
people find them easily. If a user wants to label a project, we can append
the label, e.g. 20150322-101010-FODO1.


>
>    - The user will have the ability to load both explicitly saved
>    projects and choose from a list of recent unsaved projects by date.
>
> I think we should avoid thinking about saved and unsaved projects. All
projects are saved, just like all files are saved on Google Drive and
drafts are saved in Gmail. You don't have to explicitly save anything. If
we find it useful, we can use git under the covers to keep a version
history so that the autosaves don't clobber the user's history. This will
make it easy to sync the local repo with the cloud, when we add this
feature.

Rob

**Comment by MZHarrison** [comment]
Rob,

I agree with most of your comment aside from these suggestions:

> If we name all the files by date (possibly shorter 20150322-101010) lets
people find them easily. If a user wants to label a project, we can append the label, e.g. 20150322-101010-FODO1.


When assigning a name to a project, the name shouldn't be appended to the date. When user's look for a project, they are much more likely to remember the name they assigned rather than the date it was created. Just using the name of the project will let the user find their projects quickly because they will be listed in alphabetical order in OS's file manager windows.


> I think we should avoid thinking about saved and unsaved projects. All
projects are saved, just like all files are saved on Google Drive and drafts are saved in Gmail. 



I think we should have an explicit Save command that lets the user save their project anywhere (any directory on their hard drive, to a disk or flash drive, a network location, etc.). We shouldn't force the user to keep all RadTrack projects in a RadTrack folder. When I work, I organize my files by project, not by the software i used to create a file (I don't have a Word document folder).

**Comment by robnagler** [comment]
We should perhaps discuss this on the next call. I probably don't
understand the working model for RT users.

Rob

**Comment by MZHarrison** [comment]
I've implemented a folder-based project infrastructure in my latest commits (e4614bdbaea5d594fa1ac81c59a37a10b24a6daf and 6af6028d90d85657c6299497354b361c476dd4b4). Please comment on how well you think this works. It basically works as described in my second comment (#3) above.

**Comment by bruhwile** [comment]
Great discussion. It seems like we have 90% agreement.
I suspect the remaining 10% will not impact development and can be resolved over time.

I find it very frustrating that the file browser goes to some default location when I first open the app, after which I have to browse around looking for files.

I think the above needs to be fixed for user testing at IPAC.

Below, I offer a few more thoughts regarding this topic.

I agree that RadTrack should know the location of the user workspace.
When RadTrack is opened, if it doesn't know the location of the user workspace, then it should ask the user. Not right at the beginning, but at the first time a file browser is opened.
If the user cancels out of that dialog and doesn't specify a location, then Mark's suggested locations would make a good default:
     ~/.radtrack/ in Linux
     %HOMEPATH%/RadTrack/ in Windows

RadTrack should also know where it has been installed, of course.

Whenever the user is given the option to look for an example or template Elegant file (lattice, beam, ect.), they should get a list of named files and not a file browser window. The named example files will live wherever RadTrack has been installed, and so the code will know where to find them.

**Comment by MZHarrison** [comment]
> I find it very frustrating that the file browser goes to some default location when I first open the app, after which I have to browse around looking for files.
> ...
> When RadTrack is opened, if it doesn't know the location of the user workspace, then it should ask the user. Not right at the beginning, but at the first time a file browser is opened.

I don't understand what is meant by "the user workspace." No matter what, the user is going to have to navigate to a folder the first time a file is imported. When the user starts the app, there's no way to guess what project the user is going to work on nor what files the user will need for this session. If a user has one RadTrack project for an experiment at SLAC and another for an experiment at BNL, I don't think that user would keep the two sets of files in the same place. Where should RadTrack look for files?

A shortcut to the examples and templates can be added, but I can't think of anything equivalent for files the user generates.

**Comment by bruhwile** [comment]
On Mon, Apr 13, 2015 at 10:40 PM, Mark Harrison <notifications@github.com>
wrote:

> I find it very frustrating that the file browser goes to some default
> location when I first open the app, after which I have to browse around
> looking for files.
> ...
> When RadTrack is opened, if it doesn't know the location of the user
> workspace, then it should ask the user. Not right at the beginning, but at
> the first time a file browser is opened.
>
> I don't understand what is meant by "the user workspace." No matter what,
> the user is going to have to navigate to a folder the first time a file is
> imported. When the user starts the app, there's no way to guess what
> project the user is going to work on nor what files the user will need for
> this session. If a user has one RadTrack project for an experiment at SLAC
> and another for an experiment at BNL, I don't think that user would keep
> the two sets of files in the same place. Where should RadTrack look for
> files?
>
> A shortcut to the examples and templates can be added, but I can't think
> of anything equivalent for files the user generates.
>

The first time RadTrack is launched, I agree, the user may have to hunt
around for a file to get started, or to choose a preferred workspace
location. But to have to do this every single time the program is launched,
becomes extremely tiresome.

If the program saves your workspaces in a reasonable place and you can find
them by name, most users will give up the idea of scattering them around in
the file space. Just let the software do the right thing and make life
easy. If a user really wants to 'export' a workspace file to a different
location, then that's fine, but the supported workflow doesn't have to
cater to that.

PyCharm for example, suggests a default location for your development,
where it looks by default for all 'projects'; however, it allows you to
specify a different directory, if you like. In fact, each Elegant example
comes with multiple files, and these should each be turned into an example
workspace that the user can open.

In any case, easy access to the example input and data files will solve 90%
or more of my complaint.

David

**Comment by robnagler** [comment]
We need to design for the 80% case. Microsoft Word defaults to ~/Documents,
for example, because that's where it makes sense for people to put their
files.

I strongly recommend we default to ~/RadTrack and bring a window that
suggests most recent projects. This is "normal" stuff. This is the 80%
case, not someone who has been using Elegant or SRW on their own, and wants
to try out RadTrack. We can program to this case, too, but that's not good.

We should copy in the examples into ~/RadTrack in a folder called Examples.
We should have a "Demo" button that comes up in the same window that
suggests recent projects. This will be the 80% case for the foreseeable
future. People just want to make the thing go, not come into a blank page.
It's too overwhelming.

We have to know where people keep their files so that we can mount them in
the VM. Since this is a new tool, we can dictate how people use it. For the
experts who want to use their own files, we tell them how to copy in the
files and/or have the installer copy in files to ~/RadTrack.

Our user base is not experts. Our goal is to expand reach of the product
and underlying codes, which goes beyond the experts who already know how to
use the codes. We need to abstract out the details so that graduate
students can use SRW and Elegant without having to learn the syntax of the
files or command line switches.

Rob

**Comment by MZHarrison** [comment]
Latest commits (f31aebe606f30986d4af1291aea172cf85aa27d7 and cbb2451b85363e36489477f5b28c4c98db2f4f1e) implements a menu selection for recently opened files and projects. These selections are written to a file on exit so that they are saved between RadTrack sessions, so there's less need to navigate folders to find the user's files. Once a project is created, it should be easy to get back to it quickly upon restart.

There's also menu items for loading example projects and example imports, though these are empty at the moment.

**Comment by MZHarrison** [comment]
I think what we have now works well, so I'm closing this issue. If there are problems found or changes required, a new issue should be opened.
