### ISSUE TITLE
Elegant tab fails to copy files for simulations

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#135]
If a file exists with the same name as one that the Elegant simulation tab tries to copy into the project directory, the shutil.copy2() function will throw an exception. @bruhwile, could you comment below on how you generated this error (which files you picked during the Skype call earlier today)?

**Comment by bruhwile** [comment]
1) click 'Generate Bunch' on the bunch tab.
2) click File -> Import File
3) browse local directories to select the following file:
    .../radtrack/deprecated/elegant/beamlines/aps.lte
4) select 'Elegant Bunch Transport' for tab to read the file
5) go to 'Elegant' tab, and
    a) for 'Bunch Source', choose 'Bunch'
    b) for 'Beam Line Source' choose 'Elegant Bunch Transport'
6) use the default value for 'Beam Line', which is RINGRF
7) click the 'Simulate' button
8) error popup appears


On Thu, Nov 19, 2015 at 11:37 PM, Mark Harrison <notifications@github.com>
wrote:

> If a file exists with the same name as one that the Elegant simulation tab
> tries to copy into the project directory, the shutil.copy2() function will
> throw an exception. @bruhwile <https://github.com/bruhwile>, could you
> comment below on how you generated this error (which files you picked
> during the Skype call earlier today)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/135>.
>



-- 
David Bruhwiler
RadiaSoft LLC
+1 (720) 502-3928
