### ISSUE TITLE
Ambiguous situation for files loaded into Bunch Tab

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#136]
It is unclear how the user should interact with the Bunch tab after importing a file to it that was generated externally. Below is a screenshot after importing the bunch file mentioned in #130.

![file_loaded](https://cloud.githubusercontent.com/assets/10423990/11412978/7e03a494-9398-11e5-9335-e3d3de43fb14.png)

All well and good. However, if the user clicks Generate Beam or exports the tab to a file, another beam will be regenerated with the calculated Twiss parameters, resulting in a different beam with more generic features (see below picture).

![after_generate](https://cloud.githubusercontent.com/assets/10423990/11412976/7b107c44-9398-11e5-923c-d1c3b00b8f7c.png)

At this point, the user's imported beam cannot be recovered.

So, here's the question: should the Bunch tab only be for creating new beams and not for importing beam files? I think so. There are not fine enough controls on that tab for working with non-generic beams that result from external simulations. I would suggest that the DCP tab is much more suited for viewing imported beam files--SDDS or otherwise.

I suggest removing the import capability from the Bunch tab aside from files generated by the tab.

**Comment by MZHarrison** [comment]
New bunch tab behavior as of commit 9cb7eb3ccf87d962092c84f7c9590976f6b754d1:

If the user is creating a beam, everything works as before. The Generate Bunch button was removed since the plots will be updated after every change to the Twiss tables.

If the user imports a beam file, editing the Twiss tables are disabled after calculating the Twiss parameters. This calculation happens automatically on import, so the Calculate Twiss button was removed. The user can only specify:

* The number of particles. If the number is lower than in the original file, a random sample will be extracted.
* The momentum of the bunch.
* The charge of the bunch.
* Plotting parameters

On running a simulation or exporting, these new parameters will be written to the resulting file along with the original particle data from the file (or a sample of the original).

**Comment by bruhwile** [comment]
It's no longer possible to create a new bunch from within the tab.
