### ISSUE TITLE
export of RMS momentum spread from the bunch tab

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#138]
The RMS dp/p output from Elegant, when it uses the particle distribution from the 'Bunch' tab, indicates that the Bunch tab dp/p is being interpreted as total momentum deviation.

This is wrong.

It needs to be interpreted as relative momentum deviation.

The required fix is to change how the data is exported to file from the Bunch tab.

**Comment by shaftan** [comment]
Parameters for Radtrack SRW tab:



--------------------------------------------
On Thu, 1/28/16, David Bruhwiler <notifications@github.com> wrote:

 Subject: [radtrack] export of RMS momentum spread from the bunch tab (#138)
 To: "radiasoft/radtrack" <radtrack@noreply.github.com>
 Date: Thursday, January 28, 2016, 8:16 PM
 
 The RMS dp/p output from Elegant,
 when it uses the particle distribution from the
 'Bunch' tab, indicates that the Bunch tab dp/p is
 being interpreted as total momentum deviation.
 
 This is wrong.
 
 It needs to be interpreted as relative momentum
 deviation.
 
 The required fix is to change how the data is exported to
 file from the Bunch tab.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by bruhwile** [comment]
This is essentially overlapping with issue #150
