### ISSUE TITLE
Can not run Genesis, no error reported

### ISSUE THREAD

**Issue by andonian** [radiasoft/radtrack#145]
Im trying to run the example Genesis example files in Radtrack, and get the following screen shot
<img width="1077" alt="screen shot 2016-02-22 at 3 29 17 pm" src="https://cloud.githubusercontent.com/assets/10441770/13236451/449f5b90-d979-11e5-94b1-5b1a961a5b17.png">
But the run has ended and no error reported.

More details:
I am running the visa.in file 

[visa.in.txt](https://github.com/radiasoft/radtrack/files/141620/visa.in.txt)
(which I renamed with .txt so git accepts it as an attachment)

If you run this through genesis through a terminal window, the run completes in seconds, and generates a "template.out" file with the output data.

Second attempt:
On my second attempt I tried to run "visa_time.in", which uses the "visa.beam" beam distribution file and also generates a "template.out" output file, and this completes in about 10mins in my terminal window (533 total slices).

**Comment by qedseung** [comment]
Did not running genesis from radtrack make a "template.out" file? Apologies
I still haven't gotten around to updating the list on the far right with
the outputted data files. But it should be in the radtrack directory.

**Comment by MZHarrison** [comment]
@andonian Update Radtrack and report what error message displays when you try to run a Genesis simulation. On my VM, genesis isn't installed, so the simulation can't run. If this is the case, the docker/vagrant boxes need to be updated with versions that have Genesis installed. Issue #118 is relevant here.

**Comment by robnagler** [comment]
Genesis is available in the latest VM/Docker images. 

This might work to update your VM with Genesis:

```bash
cd ~/src/radiasoft
git clone https://github.com/radiasoft/containers
cd containers/radiasoft/beamsim
bash -l codes.sh genesis
```

This will install genesis 3.2.1-beta.

**Comment by MZHarrison** [comment]
Genesis now works for me. Thanks, Rob.

**Comment by MZHarrison** [comment]
Issue resolved by installing Genesis.

Relevant new issue: #147
