### ISSUE TITLE
template.out genesis output file crashes radtrack

### ISSUE THREAD

**Issue by andonian** [radiasoft/radtrack#146]
This file 
[template.out.txt](https://github.com/radiasoft/radtrack/files/141675/template.out.txt)
"template.out" (with the added .txt so git will accept it)

crashes radtrack when trying to open in the data visualization tab

**Comment by MZHarrison** [comment]
With the commit reference above, RadTrack no longer crashes. However, this is a new kind of file, the reading of which has not been implemented. So, the user just sees an error message about not being able to read the file.

**Comment by MZHarrison** [comment]
The file attached to the original report is the output of an older version of Genesis, which is plain text instead of HDF. Are we supporting old versions?

**Comment by bruhwile** [comment]
We've gone back and forth on that question.

The short answer is 'no'.

David


On Tue, Mar 1, 2016 at 12:43 AM, Mark Harrison <notifications@github.com>
wrote:

> The file attached to the original report is the output of an older version
> of Genesis, which is plain text instead of HDF. Are we supporting old
> versions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/146#issuecomment-190599360>.
>



-- 
David Bruhwiler
RadiaSoft LLC
+1 (720) 502-3928
