### ISSUE TITLE
Simulation tabs should detect when relevant software is not installed

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#147]
Before the user attempts to run a simulation, RadTrack should check if the relevant software can be run. The simplest thing would be to put the following code in the `__init__()` function of the simulation tabs (RbEle, genesis_controller, etc.):

```
# Example for elegant
if QtCore.QProcess.execute('which', ['elegant']):
    response = QtGui.QMessageBox.question(self,
        "Install Elegant",
        "Elegant is not installed. Would you like to install it now?",
        QtGui.QMessageBox.Yes | QtGui.QMessageBox.No)

    if response = QtGui.QMessageBox.Yes:
        # check if /home/vagrant/src/radiasoft/containers/beamsim/ exists
        # git clone if not
        # switch to /home/vagrant/src/radiasoft/containers/beamsim/
        # bash -l codes.sh elegant
    else:
        # close current tab
````

**Comment by MZHarrison** [comment]
Given @robnagler comment here: https://github.com/radiasoft/radtrack/issues/145#issuecomment-192089272, this might not actually be an issue.

**Comment by robnagler** [comment]
We should make sure we deliver RadTrack with all the relevant software in a
Docker or VirtualBox image.

If you decide to test for an implementation, I recommend providing stock
configurations and trying to run the programs themselves. It's insufficient
to see if a program exists. It may be the wrong program, the libraries may
not be available, or it might be the wrong version.

BTW, "which" should be replaced by "type -t". which is a bash function, and
type is a builtin.

**Comment by MZHarrison** [comment]
Right. Simulation codes should come pre-installed in the containers.
