### ISSUE TITLE
functions not implemented in elegant template

### ISSUE THREAD

**Issue by qedseung** [radiasoft/radtrack#148]
there are functions in the examples for optimization, applying errors, applying corrections, etc... in the elegant examples not implemented in the elegant template. Going through the documentation I list all of them here:

alter elements
application factors
analyze map
aperture data
change particle
chromaticity
closedorbit
correction matrix output
correct tunes
coupled twist output
divideelements
errorelement
error control
find aperture
floor coordinates
frequency map
global settings
insert elements
insert sc effects
linear chromatic tracking setup
link control
linkelements
load parameters
load output
matrixoutput
modulate elements
momentsoutput
momentum aperture
optimize
optimizationcoverable 
optimization setup
optimization variable
parallel optimization setup
print dictionary
rampelements
rfsetup
rpnevxpression
rpnload
SASEFEL
save lattice
semaphores
slice analysis
subprocess
steering element
transmuteelement
tunefootprint
twissanalysis
tuneshiftwithamplitude
vary element

**Comment by bruhwile** [comment]
Some of these should be supported.
This requires the ability to import ELE files.
The GUI should allow the user to see what is in the ELE file and perhaps modify/set parameters.
All of the standard Elegant example files should work with the new ELE importer.

**Comment by MZHarrison** [comment]
Commit 32249dd4047b00a54470d372b0783fe95c58cc0d (see issue #152) now allows users to directly edit both imported and generated `.ele` files. More GUI tools for working with `.ele` files can be added as needed.
