### ISSUE TITLE
6D phase space sdds files unknown units

### ISSUE THREAD

**Issue by qedseung** [radiasoft/radtrack#149]
Example sdds files have empty parameterData field which would have told us the units of the data columns, specifically the momentum

**Comment by bruhwile** [comment]
this is overlapping with issue #150 
note that the average value of beta*gamma can be extracted from the data in the SDDS file.
however, the particle mass is unknown
probably should ask the user to specify interactively when importing an SDDS file...
we leave this to a future issue.
