### ISSUE TITLE
speed up bunch generation

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#2]
Generating the bunch distribution natively within RadTrack can probably be much faster.

**Comment by MZHarrison** [comment]
Fixed in commits 9cb7eb3ccf87d962092c84f7c9590976f6b754d1 and https://github.com/radiasoft/radtrack/commit/9d8d36f28a9f5d45f2a9093ad281b52f295351db. Turns out, generating a bunch was fast. It was plotting that was slow for too many particles.
