### ISSUE TITLE
Bunch tab cuts off text in Mac

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/radtrack#21]
I'm not sure if other people are seeing this, but the text is being cut off on the labels, and the boxes with the parameters are too small. This is at full screen on my 15" MacBook Pro. I seem to recall this issue in the FEL tab as well, and we fixed it at the last LA meeting.

![bunch](https://cloud.githubusercontent.com/assets/7430829/6254880/0b40bb6a-b769-11e4-894a-39c8be5e471d.png)

**Comment by sdwebb** [comment]
Changes fixed partially. Attached is how the window looks now. Note that the spreadsheets for the beam parameters are getting cut off. Also, missing the last parenthesis in the Twiss Parameter label.

![clipping](https://cloud.githubusercontent.com/assets/7430829/6335688/7397aa6c-bb5a-11e4-9afd-fcafa81e0ab8.png)

**Comment by qedseung** [comment]
Have made the the label change and the spreadsheets bigger closing issue for now
