### ISSUE TITLE
modify tabs so they can be launched independently

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#34]

**Comment by MZHarrison** [comment]
Why do we want tabs to be launched independently? How would this be different than, as an example, starting RadTrack with no tabs loaded and letting the user choose which tabs to load from the Tab menu?

**Comment by bruhwile** [comment]
This originated as a request from Timur, I think.
The idea is that a developer working on a particular tab could repeatedly
launch the tab of interest.

I do think that RadTrack should launch with no tabs at all, but rather with
a dialog asking the user what they want to do -- simulate an accelerator,
model synchrotron radiation, design a free electron laser, etc. Based on
their response the appropriate tab would open up.

For the beta_test mode, I just changed it so that only the Elegant tab is
opened. Other related tabs can be opened as needed. This is less confusing
for the user.

David

On Tue, Apr 28, 2015 at 11:41 AM, Mark Harrison <notifications@github.com>
wrote:

> Why do we want tabs to be launched independently? How would this be
> different than, as an example, starting RadTrack with no tabs loaded and
> letting the user choose which tabs to load from the Tab menu?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/34#issuecomment-97146943>.
>



-- 
David Bruhwiler
RadiaSoft LLC
+1 (720) 502-3928
