### ISSUE TITLE
choose data structure for exchange of physical variables between tabs

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#36]
Should it be a list of lists?
Dictionary, etc., etc.?

**Comment by robnagler** [comment]
Is this related to the spreadsheet with configuration parameters?

I would like to have classes so we can refer to the names like `cfg.BeamP.alphax` to get that value. We would generate these classes dynamically from the spreadsheet. We could add converters if, say, a particular structure is required, e.g. `arPrecF` seems to be an array constructed from heterogenous values (initial UR harmonic, final UR harmonic, etc.).

By having variables bound to named values (vs dict), we can bind metadata to them for types, default values, etc. These can them be used to parse config files for setting up these variables.

Maybe I'm totally off the mark here...

**Comment by bruhwile** [comment]
Yes. That all sounds good.

I know we had this conversation once or twice already, but I wanted to
document the decision and clarify the next step.

I believe the next steps are:
   1) decide on the names for the physical groupings and the contained
variables, as defined in the Excel file
             .../radtrack/docs/physParams/UnifiedParameters.xlsx
   2) write the parser to scrape the Excel file and generate the desired
classes
   3) decide how to handle secondary parameters and differing conventions
for variable name/units/normalization, etc.

I'll close this issue and create new issues for 1) and 2), assigning them
to me and you, respectively.
I think 2) can proceed as soon as the Excel file is cleaned up just a
little.

Thanks,
David

On Mon, Feb 23, 2015 at 2:19 PM, Rob Nagler <notifications@github.com>
wrote:

> Is this related to the spreadsheet with configuration parameters?
>
> I would like to have classes so we can refer to the names like
> cfg.BeamP.alphax to get that value. We would generate these classes
> dynamically from the spreadsheet. We could add converters if, say, a
> particular structure is required, e.g. arPrecF seems to be an array
> constructed from heterogenous values (initial UR harmonic, final UR
> harmonic, etc.).
>
> By having variables bound to named values (vs dict), we can bind metadata
> to them for types, default values, etc. These can them be used to parse
> config files for setting up these variables.
>
> Maybe I'm totally off the mark here...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/36#issuecomment-75635929>.
>



-- 
David Bruhwiler
RadiaSoft LLC
+1 (720) 502-3928
