### ISSUE TITLE
SRW variables for 1electron and bunch cases

### ISSUE THREAD

**Issue by shaftan** [radiasoft/radtrack#39]
Steve S., all,

I summarized the list of SRW variables, their names and initial setpoints in the attached xls file.

1electron: UndParamsThin, BeamParams(Common), PrecisionThin, wfr
bunch: UndParamsThick, BeamParams (Common), PrecisionThick

The page "Templates" correspond to the presets data for 1electron (Thin) and bunch (Thick) cases.

Pages ID... correspond to the test cases with Insertion Devices at existing light sources.

**Comment by bruhwile** [comment]
I've added the corresponding Excel file to the repository
    ...\radtrack\docs\physParams\SRWTestCases.xlsm
