### ISSUE TITLE
directory structure, setup.py, tests?

### ISSUE THREAD

**Issue by robnagler** [radiasoft/radtrack#40]
I'm starting to write units tests, and I'd like to be able to say:

```python setup.py test```

That doesn't work, because we don't have a directory structure that supports it. We also want
to be able to build with `setup.py`. With this in mind, I propose the following global changes:

* Move down all the `*.py` files to `radtrack/`. 
* Instead of having `import radtrack.RadTrack.genesis.genesis`, drop the `RadTrack` directory. There are no conflicts with this change.
* Move the current `test` directory to `examples`.
* Create a `tests` directory for self-checking unit tests.
* Use virtualenv per project so that `pip freeze` works properly to create `requirements.txt`.
* Create a `bin` directory for the main program, `radtrack.py', which would call `radtrack.RbGlobal.main`
* Use `pip install -e .` to allow `bin/radtrack.py` to import the right modules.
* Rename `license.md` to `LICENSE` (just a nit)

I can write a script to fix up the imports automatically. I didn't see anything complicated (e.g. calling `importlib`).

The ultimate goal to my mind is to get our tests running with an automatic integration site like [Travis](travis-ci.org).

Thoughts?

**Comment by bruhwile** [comment]
I like it. Thanks, Rob.

Unless there are objections, everyone please commit your changes to the
repository by 4 pm PST / 5 pm MST / 7 pm EST

If this is a problem, let Rob know.
If your changes are already checked in, then it would be nice to let Rob
know off-list.

Rob - please make the changes at your earliest convenience after 5 pm
today, or as soon as you hear from everyone.

Thanks,
David


On Thu, Mar 5, 2015 at 9:27 AM, Rob Nagler <notifications@github.com> wrote:

> I'm starting to write units tests, and I'd like to be able to say:
>
> python setup.py test
>
> That doesn't work, because we don't have a directory structure that
> supports it. We also want
> to be able to build with setup.py. With this in mind, I propose the
> following global changes:
>
>    - Move down all the *.py files to radtrack/.
>    - Instead of having import radtrack.RadTrack.genesis.genesis, drop the
>    RadTrack directory. There are no conflicts with this change.
>    - Move the current test directory to examples.
>    - Create a tests directory for self-checking unit tests.
>    - Use virtualenv per project so that pip freeze works properly to
>    create requirements.txt.
>    - Create a bin directory for the main program, radtrack.py', which
>    would callradtrack.RbGlobal.main`
>    - Use pip install -e . to allow bin/radtrack.py to import the right
>    modules.
>    - Rename license.md to LICENSE (just a nit)
>
> I can write a script to fix up the imports automatically. I didn't see
> anything complicated (e.g. calling importlib).
>
> The ultimate goal to my mind is to get our tests running with an automatic
> integration site like Travis <http://travis-ci.org>.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/40>.
>



-- 
David Bruhwiler
RadiaSoft LLC
+1 (720) 502-3928

**Comment by robnagler** [comment]
Let me test the script (which I've yet to write :) first. We can then
schedule the change. This type of change is best done on a weekend imiho.
Everybody probably checks in by Fri anyway.

Rob

**Comment by bruhwile** [comment]
OK.

In my previous message, postpone the 4 pm PST / 5 pm MST / 7 pm EST
deadline for finalizing check-ins to Friday (tomorrow).

Then presumably Rob will finish the restructuring by Monday morning.

Thanks,
David


On Thu, Mar 5, 2015 at 9:35 AM, Rob Nagler <notifications@github.com> wrote:

> Let me test the script (which I've yet to write :) first. We can then
> schedule the change. This type of change is best done on a weekend imiho.
> Everybody probably checks in by Fri anyway.
>
> Rob
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/40#issuecomment-77397796>.
>



-- 
David Bruhwiler
RadiaSoft LLC
+1 (720) 502-3928

**Comment by robnagler** [comment]
The rename is complete. I believe everything should work, but please let me know if there are problems.

To run RadTrack (for now) on Linux or OS X, do:

```bash
PYTHONPATH="$PWD" python radtrack/RbGlobal.py
```

On Windows:

```
set PYTHONPATH=%cd%
python radtrack/RbGlobal.py
```

I'll get a `setup.py` and a "bin" script added asap so you can use `pip -e install .` 

Most of the time was getting the right dependencies installed on my VM under pyenv/virtualenv. This was helpful in any event, because I know how to compile many of the parts on Linux (see [install/README](https://github.com/radiasoft/radtrack/blob/master/install/README.md#linux-build) for details). In particular, I figured out how to get QT4 to compile relatively quickly by limiting all the unnecessary parts. All of this work is an important part of the containerization work.

**Comment by bruhwile** [comment]
Awesome. Thanks!
David

**Comment by MZHarrison** [comment]
I have tried to run `RbGlobal.py` (with both `python RbGlobal.py` and Rob's instructions above) and I get `ImportError`s:

    Traceback (most recent call first):
      File "RadTrack/RbGlobal.py", line 12, in <module>
        from radtrack.globalgu import Ui_globalgu
    ImportError: No module name radtrack.globalgu

Changing the line in question to

    from globalgu import Ui_globalgu

Gets rid of the error and displays another error on the next import statement:

    from  radtrack.RbLaserWindow import RbLaserWindow

For each error, deleting `radtrack.` fixes the error. Since `RbGlobal.py` is in the same directory as `globalgu.py`, `RbLaserWindow.py`, etc., the extra directory is causing errors. `radtrack.` needs to be removed from all import statements in all files recursively in the RadTrack directory

**Comment by robnagler** [comment]
You need to be in the top level directory. I'll be explicit:

```bash
git clone https://github.com/radiasoft/radtrack
cd radtrack
PYTHONPATH="$PWD" python radtrack/RbGlobal.py
```

There is now a `setup.py` so you can do this once:

```bash
git clone https://github.com/radiasoft/radtrack
cd radtrack
python setup.py develop
python -m radtrack.RbGlobal

@robnagler

**Comment by MZHarrison** [comment]
OK. RbGlobal.py works. Where can I acquire `pybivio` to run `python setup develop`?

**Comment by robnagler** [comment]
Sorry, do this:

```
git clone https://github.com/biviosoftware/pybivio
cd pybivio
python setup develop
```

Then you can go into `radtrack` and run `python setup develop`.

I just fixed some `RbUtility` import errors. If there are other relative imports, we should find them.

Also, I added `bin/radtrack`. This should work on the Mac and Linux. I need to figure out how to make it portable to windows. When you do a `python setup.py develop`, it will install `radtrack` as a script in your virtualenv, and then you can just run `radtrack` from anywhere.

**Comment by MZHarrison** [comment]
Got it. Thanks.

**Comment by robnagler** [comment]
Got the script thing figured out. `distutils` has an `entry_points` feature which enables portable script creation. I added the file `radtrack/radtrack_gui.py` which invokes `RbGlobal.main` with `sys.argv`. `pybivio.b_setup.setup` searches for files named `<proj>/*_gui.py` and `<proj>/*_console.py` and creates the appropriate `entry_points` values. In our case, we have `radtrack/radtrack_gui.py` which creates the program `radtrack.exe` on Windows and `radtrack` on Linux.

You'll need to:

```bash
cd pybivio
git pull
cd ../radtrack
git pull
python setup.py develop
```

I think when `setup.py` changes, you'll need to do the last line. Otherwise, you just need the `git pull`.

Please let me know if you have problems

/cc @robnagler

**Comment by qedseung** [comment]
Hello,
I just did a pull this morning and tried to run radtrack but got this error:

Traceback (most recent call last):

  File "//anaconda/bin/radtrack", line 6, in <module>

    exec(compile(open(__file__).read(), __file__, 'exec'))

IOError: [Errno 2] No such file or directory:
'/Users/stevenseung/Desktop/radtrack/bin/radtrack'


Is there no more bin folder?


Sincerely,

Steven Seung

On Mon, Mar 9, 2015 at 4:27 PM, Rob Nagler <notifications@github.com> wrote:

> Got the script thing figured out. distutils has an entry_points feature
> which enables portable script creation. I added the file
> radtrack/radtrack_gui.py which invokes RbGlobal.main with sys.argv.
> pybivio.b_setup.setup searches for files named <proj>/*_gui.py and
> <proj>/*_console.py and creates the appropriate entry_points values. In
> our case, we have radtrack/radtrack_gui.py which creates the program
> radtrack.exe on Windows and radtrack on Linux.
>
> You'll need to:
>
> cd pybivio
> git pullcd ../radtrack
> git pull
> python setup.py develop
>
> I think when setup.py changes, you'll need to do the last line.
> Otherwise, you just need the git pull.
>
> Please let me know if you have problems
>
> /cc @robnagler <https://github.com/robnagler>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/40#issuecomment-77966644>.
>



-- 
Radiabeam Technologies
1717Stewart St
Santa Monica, CA 90404
310-822-5845

**Comment by robnagler** [comment]
Git on Windows does not do the right thing with case-changing directory
names (RadTrack => radtrack).

I recommend you do this:

cd radiasoft (or wherever you store your git repo files)
rename radtrack radtrack-old
git clone https://github.com/radiasoft/radtrack
cd radtrack
python setup.py develop

Then the installed "radtrack" script should work.

If you have an older version of Anaconda, there may be issues with setup.py
trying to install scipy. Just upgrade to the newest Anaconda, and all the
versions should be ok.

Rob

**Comment by qedseung** [comment]
Now I'm getting this error:

No local packages or download links found for pybivio>=0.1

error: Could not find suitable distribution for
Requirement.parse('pybivio>=0.1')


There is a pybivio folder when I cloned radtrack again. All though the
folder where I store the repo is just called radtrack on my desktop, and it
was kind of like that before with a radtrack inside of radtrack. So I
assume you want to rename the radtrack that's inside the repository? Also
should it matter since when I cloned it replaced the whole folder so there
is no "radtrack-old".


What changed? The "radtrack" script was working for me on monday.


Sincerely,

Steven Seung

On Wed, Mar 11, 2015 at 9:50 AM, Rob Nagler <notifications@github.com>
wrote:

> Git on Windows does not do the right thing with case-changing directory
> names (RadTrack => radtrack).
>
> I recommend you do this:
>
> cd radiasoft (or wherever you store your git repo files)
> rename radtrack radtrack-old
> git clone https://github.com/radiasoft/radtrack
> cd radtrack
> python setup.py develop
>
> Then the installed "radtrack" script should work.
>
> If you have an older version of Anaconda, there may be issues with setup.py
> trying to install scipy. Just upgrade to the newest Anaconda, and all the
> versions should be ok.
>
> Rob
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/40#issuecomment-78304445>.
>



-- 
Radiabeam Technologies
1717Stewart St
Santa Monica, CA 90404
310-822-5845

**Comment by robnagler** [comment]
I'm sorry for not being clear.

I think we need to agree on some way of talking about where we all develop.
My model is this:

<home>/
    src/
        radiasoft/
            radtrack/
        biviosoftware/
            pybivio/

This mirrors how github does things, that is, all repos have a
user/organization and a repository name.

Assuming the above, here's what you need to do:

cd %HOME%
mkdir src
cd src
mkdir biviosoftware
cd biviosoftware
git clone https://github.com/biviosoftware/pybivio
cd pybivio
python setup.py develop
mkdir radiasoft
cd radiasoft
git clone https://github.com/radiasoft/radtrack
cd radtrack
python setup.py develop


You shouldn't need to run setup.py again (although it doesn't hurt) unless
scripts are added. I'll try to mention this on new releases.

I hope this works. If it doesn't, feel free to skype me (robnagler), and we
can try to figure this out.

Rob

**Comment by robnagler** [comment]
There were several mistakes in my email, sorry.

The formatting of this was in a fixed font in my email, but it isn't
showing up that way after it was reflected by Github, so I'll try some
ascii art:

<home>/
____src/
________radiasoft/
_____________radtrack
________biviosoftware/
_____________pybivio/

In bash, you'd create this structure with:

mkdir -p ~/src/radiasoft/radtrack ~/src/biviosoftware/pybivio

The MS cmd shell instructions were off. It's missing a 'cd ..\..' (labelled
as #NEW below)


cd %HOME%
mkdir src
cd src
mkdir biviosoftware
cd biviosoftware
git clone https://github.com/biviosoftware/pybivio
cd pybivio
python setup.py develop
cd ..\.. #NEW

mkdir radiasoft
cd radiasoft
git clone https://github.com/radiasoft/radtrack
cd radtrack
python setup.py develop

Please let me know if any of this is unclear. I apologize for the errors in
my previous email.

Rob

**Comment by bruhwile** [comment]
This issue has gone on long enough, and I think most questions have been answered.
Related matters should be addressed by opening new issues.
