### ISSUE TITLE
Beta invocation mode for RbGlobal

### ISSUE THREAD

**Issue by robnagler** [radiasoft/radtrack#43]
In order to facilitate beta testing, we are going to limit the number of tabs which are "beta ready" in the initial display at RbGlobal startup.

**Comment by robnagler** [comment]
Changed the command line parsing of RbGlobal to use the `argh` library so we could invoke with a --beta-test flag. This produces automatic help with `radtrack -h` or `radtrack --help`. 

There is now a `project_file` positional argument to `RbGlobal.main`, which is optional by an `argh` decorator (calling `argparse` under the covers).

`install/radtrack_win32.py` was modified to call `RbGlobal.main` with `beta_test=True`.

Changed the `RbGlobal` constructor to accept `beta_test` and to open the tabs I think are going to be required for beta test. David, it should be obvious how this works so you can change my guesses on the tabs.

**Comment by bruhwile** [comment]
This has been completed.
