### ISSUE TITLE
sddsdata does not work on Unix

### ISSUE THREAD

**Issue by sdwebb** [radiasoft/radtrack#45]
I have tried importing the sddsdata module on both OS X and Linux and have gotten the error:

```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-957a24b15427> in <module>()
----> 1 import radtrack.dcp.sddsdata as sddsdata

ImportError: /home/swebb/proj/radtrack/radtrack/dcp/sddsdatamodule.so: invalid ELF header
```
This is both on my laptop (OS X) and on the apa11 Linux system.

A few questions on this point
1. Have we successfully read in any .sdds file on a non-Windows platform?
2. Should the sddsdata class work in radtrack directly, or are there more complicated build issues?
3. If there are more complicated build issues, are they documented and if so where?

**Comment by robnagler** [comment]
It's a Mach-O (Mac OS X) file so it won't run on Linux:

$ file sddsdatamodule.so
sddsdatamodule.so: Mach-O universal binary with 2 architectures
sddsdatamodule.so (for architecture i386): Mach-O dynamically linked shared
library i386
sddsdatamodule.so (for architecture x86_64): Mach-O 64-bit dynamically
linked shared library x86_64

Python complains about the syntax:

ImportError: dynamic module does not define init function
(initsddsdatamodule)

I'm working on an auto-installer for Linux. As a part of this process, I
would like to run the 3rd party programs. I have run examples at times, but
it would be better for us to have some real examples, which I can turn into
automated tests. So, either check-in some files to examples/ or email them
to me with instructions on how to run them.

It's like the auto-installer will work on Mac OS X as well. I'll test that
after containerizing the installer for Linux.

Rob

**Comment by robnagler** [comment]
If you are on Linux, you can install one of the `SDDSPython` packages [from this list at ANL](http://www.aps.anl.gov/Accelerator_Systems_Division/Accelerator_Operations_Physics/installationGuide_Linux.shtml)

The files need to be installed in virtualenv in the user's home directory so I added that to the system build scripts.

**Comment by bruhwile** [comment]
It looks like this has been done on dev.radiasoft.org
Closing.
