### ISSUE TITLE
execution of physics engines should be asynchronous

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#49]
At present, if Elegant or another RadTrack code hangs, it hangs the UI.
This needs to be corrected.

**Comment by MZHarrison** [comment]
It looks like the proper way to do this is to use `subprocess.Popen()` to run the simulation (Elegant, etc.) in a new process and `threading.Thread()` to monitor it in a separate execution thread until it completes. An example for Elegant in the `RbEle` class would look like this:

    def runSimulation(self):
        # ... create input file ...
        elegantProc = subprocess.Popen(['elegant', inputFile])
        elegantMonitor = threading.Thread(target = self.asyncWaitForSimulationEnd, elegantProc)
        elegantMonitor.start()
        return


    def asyncWaitForSimulationEnd(self, proc):
        self.textBox.setText('Simulation started ...')
        proc.wait()
        self.textBox.setText('Simulation complete!')

This starts Elegant, starts the monitor, and immediately returns control to the user.

**Comment by bruhwile** [comment]
I attach here the Python code that Timur wrote to implement a progress bar
for Elegant simulations.
It's relevant to this thread, and it would be very cool to implement.
This would satisfy the 'feedback to user that Elegant is running' issue.

David

**Comment by robnagler** [comment]
David, didn't see your code. You might post as a gist and share the link
here.

**Comment by robnagler** [comment]
Mark, I think we would want to use QProcess, not python threading. When you
are programming in GUI toolkits, I've found that it is useful to stay
within their asynchronous event model to avoid conflicts/deadlocks.

**Comment by bruhwile** [comment]
The code (Timur wrote it, not me) was attached to the message as
ElegantOut1.py but GitHub issues don't allow any file attachments other
than images, so I guess it was stripped off the message. That's annoying.

Never heard of gists, but here they are:
https://gist.github.com/

This is interesting. I like it.

Since the code is Timur's, I created a 'private' gist here:
   https://gist.github.com/bruhwile/07fb33d77faaf24215d4

David

**Comment by robnagler** [comment]
The readline approach is likely to be too simple.

We will want to use QProgressBar.

We will want a reasonable estimate for how long Elegant takes to run on a
given dataset.

**Comment by shaftan** [comment]
Rob, 
The current jobs of Elegant are managed by .ele file and it may be too difficult to predict upfront how long different jobs will take. 
Alternatively the progress bar can report on completion of a given fraction of a given job (as in our example).Timur.

**Comment by robnagler** [comment]
Yes, I can imagine estimating run-time is difficult. I still think we will
want to guess within an order of magnitude and to update the guess as we
get more elapsed times from the various phases. Having a phase based
progress bar is not going to be as useful to a new Elegant user as a
time-based one.
