### ISSUE TITLE
change use of energy input on Elegant tab

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#55]
If the user selects a 'Bunch' tab as the data source, then the beam energy box should be filled from the energy specified on that tab.

If the user selects an external particle file, then they need to specify the beam energy manually.

The default order and num step boxes should be removed from the GUI.

**Comment by MZHarrison** [comment]
This will also solve the problem with the proper format for entering the momentum. Right now, the momentum box is written to a .ele file as "p_central = <user input>". This value should be beta*gamma. If momentum in MeV/c is desired, then the line would need to be changed to "p_central_mev = <user input>". In any case, a <user input> of "65_mev" is not valid, and I'm a bit surprised that Elegant didn't encounter an error.

**Comment by bruhwile** [comment]
Thanks for figuring this out, Mark.

General comment:  This makes it clear that the Elegant use cases should be
completely specified for the integration tests, and the results should be
understood, so we know for sure that the code is doing exactly what's
requested. The use cases can be left a little vague for user testing
purposes.

David
