### ISSUE TITLE
X11 fonts wrong size

### ISSUE THREAD

**Issue by robnagler** [radiasoft/radtrack#60]
When I bring up RadTrack on XQuartz on my Mac, the fonts overflow the tabs. To fix this, I did this on my Mac in an xterm:

```
echo 'Xft.dpi: 96' >> ~/.Xresources
xrdb -merge ~/.Xresources
```

Now the tabs display correctly, but this is a workaround. There needs to be some auto-sizing code.

**Comment by bruhwile** [comment]
I think I fixed this issue a long time ago.
Are others still seeing this problem?
