### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by robnagler** [radiasoft/radtrack#65]
All exceptions need to be caught by the main loop, logged (remotely if possible), and presented to the user with a reasonable choice. We can't know about all errors other than there will always be bugs. Therefore, we need an error handling architecture that traps errors safely, allowing the program to continue operating or restarting automatically. 

User data should be saved, if possible, before errors occur and at the time of the error. This relates to the external versioning of user data (see email dated 3/24/15 15:51 MT for more thoughts).

**Comment by MZHarrison** [comment]
Here's an idea from the PyQt mailing list for catching all exceptions and displaying a dialog box allowing the user to submit a bug report.

http://www.riverbankcomputing.com/pipermail/pyqt/2009-May/022961.html
