### ISSUE TITLE
Dynamic tracing

### ISSUE THREAD

**Issue by robnagler** [radiasoft/radtrack#66]
RT has lots of code that looks like:

```python
if False:
    print ' '
    print ' Here is mySDDS.columnData[:]:'
    print mySDDS.columnData
```

This is useful tracing, but you have to edit the code and restart the program to cause it to be written.

Bivio has a library from another open source project, which we will add to PyBivio that allows you to control this output dynamically through regular expression matching. For example, you would write something like:

```python
trace('mySDDS.columnData = {}', mySDDS.columnData)
```

Then when you start the program with, say:

```bash
radtrack --trace='RbBunchWindow'
```

Any trace statement executed from `RbBunchWindow.py` would get output. We could add a button to open a popup to dynamically modify the regular expression.

`trace` calls are efficient unless tracing is turned on, that is, if there's no regular expression, the `trace` function returns after a single `if`.

If someone has another tracing module they'd like to use, I'll be happy to take a look. I've been using this type of dynamic tracing for three decades (yikes!), and I've found it indispensable.

**Comment by bruhwile** [comment]
This sounds good to me. Let's use it.

I don't know of any other tracing modules.

David
