### ISSUE TITLE
Remove sdds distro files from radtrack/dcp/

### ISSUE THREAD

**Issue by robnagler** [radiasoft/radtrack#67]
Now that we know how to install SDDS Python on Linux, we should do the same on Windows. The installer is here: http://www.aps.anl.gov/Accelerator_Systems_Division/Accelerator_Operations_Physics/software.shtml#PythonBinaries

Once everybody has install SDDS Python properly, we can remove the SDDS modules. 

There's now an radtrack.util.sdds_fix module which hides the sdds import issue. It tries to import the system sdds, and if that fails, it tries radtrack.dcp.sdds. Once people install SDDS properly, we can remove sdds_fix.

**Comment by bruhwile** [comment]
I've done this on Win8.
There's something about the 64-bit version of the sddsdata library that's
not working on my system.

Everything works fine in 32-bit, so I'm not planning to investigate further.

David

**Comment by bruhwile** [comment]
I know Rob deleted the files from the repo earlier today.
I'm closing this issue.
