### ISSUE TITLE
some SRW default cases are not working

### ISSUE THREAD

**Issue by qedseung** [radiasoft/radtrack#68]
Some of the SRW test cases do not work:
"Thin" Case:
1. dependent argument = e&x&y : results in a index out of range error
"Thick" Case:
1. dependent argument = y : results in a index out of range error
2. dependent argument = e&x, e&y : nothing happens
3. dependent argument = e&x&y : generic error printed out

**Comment by shaftan** [comment]
Steve, I will look into this over the weekend.Best regards,Timur.

**Comment by qedseung** [comment]
I think I may have found the source of the error while making the excel
file containing the default values for SRW. The thin and thick tables I
used are different from the ones in the srwtestcases.xls.xls file. I based
the ones in python on tables I got in an email. I also have some question
about variable names, if you have time to talk tomorrow?

Regards,
Steven Seung

On Wed, Mar 25, 2015 at 8:15 PM, shaftan <notifications@github.com> wrote:

> Steve, I will look into this over the weekend.Best regards,Timur.
>
> From: qedseung <notifications@github.com>
> To: radiasoft/radtrack <radtrack@noreply.github.com>
> Cc: shaftan <tshaftan@yahoo.com>
> Sent: Wednesday, March 25, 2015 8:28 PM
> Subject: [radtrack] some SRW default cases are not working (#68)
>
> Some of the SRW test cases do not work:
> "Thin" Case:
> 1. dependent argument = e&x&y : results in a index out of range error
> "Thick" Case:
> 1. dependent argument = y : results in a index out of range error
> 2. dependent argument = e&x, e&y : nothing happens
> 3. dependent argument = e&x&y : generic error printed out—
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/68#issuecomment-86321042>.
>



-- 
Radiabeam Technologies
1717Stewart St
Santa Monica, CA 90404
310-822-5845

**Comment by shaftan** [comment]
Steve, we can talk at 7:30 pm NY time today if this time works for you.Best regards,
Timur.

**Comment by qedseung** [comment]
okay

On Fri, Mar 27, 2015 at 10:10 AM, shaftan <notifications@github.com> wrote:

> Steve, we can talk at 7:30 pm NY time today if this time works for
> you.Best regards,
> Timur.
>
> From: qedseung <notifications@github.com>
> To: radiasoft/radtrack <radtrack@noreply.github.com>
> Cc: shaftan <tshaftan@yahoo.com>
> Sent: Thursday, March 26, 2015 9:03 PM
> Subject: Re: [radtrack] some SRW default cases are not working (#68)
>
>
> I think I may have found the source of the error while making the excel
> file containing the default values for SRW. The thin and thick tables I
> used are different from the ones in the srwtestcases.xls.xls file. I based
> the ones in python on tables I got in an email. I also have some question
> about variable names, if you have time to talk tomorrow?
>
> Regards,
> Steven Seung
>
> On Wed, Mar 25, 2015 at 8:15 PM, shaftan <notifications@github.com> wrote:
>
> > Steve, I will look into this over the weekend.Best regards,Timur.
> >
> > From: qedseung <notifications@github.com>
> > To: radiasoft/radtrack <radtrack@noreply.github.com>
> > Cc: shaftan <tshaftan@yahoo.com>
> > Sent: Wednesday, March 25, 2015 8:28 PM
> > Subject: [radtrack] some SRW default cases are not working (#68)
> >
> > Some of the SRW test cases do not work:
> > "Thin" Case:
> > 1. dependent argument = e&x&y : results in a index out of range error
> > "Thick" Case:
> > 1. dependent argument = y : results in a index out of range error
> > 2. dependent argument = e&x, e&y : nothing happens
> > 3. dependent argument = e&x&y : generic error printed out—
> > Reply to this email directly or view it on GitHub.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/radiasoft/radtrack/issues/68#issuecomment-86321042>.
>
> >
>
>
>
> --
> Radiabeam Technologies
> 1717Stewart St
> Santa Monica, CA 90404
> 310-822-5845
>
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/68#issuecomment-87015039>.
>



-- 
Radiabeam Technologies
1717Stewart St
Santa Monica, CA 90404
310-822-5845

**Comment by shaftan** [comment]
Corrected errors below, fixed plot labels, fixed units, reworked two table of presets. Uploaded 2 files to github: RbSrwsingleA.py and RbSrmultiA.pyReady for testing.
Timur.

**Comment by shaftan** [comment]
Modified and debugged analytic calculations. New files -- AnalyticCalc.py, RbSrwsingleA.py and RbSrwmultiA.py
