### ISSUE TITLE
Tab classes require RbGlobal recognized methods

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#7]
All classes specifying tabs in RbGlobal need the following methods:
- ~~`hasChanged()` returns True/False to indicate that a tab's data has changed and needs saving;~~
- `importFile(fileName)`, `exportToFile(fileName)` for loading and saving;
- `acceptsFileTypes`  (list of file extensions) for indicating what kinds of files it can read (default file extension should be listed first)

**Comment by MZHarrison** [comment]
I've removed the hasChanged code from RbGlobal and all tabs (commit 174dd3629f372b0467aca665b1e1398b0979930b). Everything is saved on exit (or, perhaps in a future iteration, periodically as the user works).

**Comment by MZHarrison** [comment]
A note about `exportToFile()` and `acceptsFileTypes`: the default (first) file extension in `acceptsFileTypes` should be a file format that can hold all of the information in the tab so that, when the file is imported into the tab, the tab is restored to the state at the time of export.

**Comment by MZHarrison** [comment]
Update:

Tabs that still need these functions and attributes:

 - RbSrwTab.py
 - LaserTab.py
 - genesis/rbgenesis2.py

**Comment by MZHarrison** [comment]
I'm closing this issue since issues #95, #94, and #73 cover the remaining work to be done.

**Comment by qedseung** [comment]
The genesis code is no where near running, just have that space holder gui.
Is Radtrack giving warnings trying to initialize it? Can we just skip it
from loading genesis? Or is it fine to leave it, as we'll need those
functions in the actual genesis code?

On Fri, May 8, 2015 at 2:31 PM, Mark Harrison <notifications@github.com>
wrote:

> I'm closing this issue since issues #95
> <https://github.com/radiasoft/radtrack/issues/95>, #94
> <https://github.com/radiasoft/radtrack/issues/94>, and #73
> <https://github.com/radiasoft/radtrack/issues/73> cover the remaining
> work to be done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/7#issuecomment-100374008>.
>



-- 
Radiabeam Technologies
1717Stewart St
Santa Monica, CA 90404
310-822-5845

**Comment by MZHarrison** [comment]
It's fine to leave it as is. The Genesis tabs don't cause any problems with running RadTrack. When you close RadTrack, you'll see messages printed about various tabs that can't be saved properly (Laser, SRW, and Genesis2). Those errors/warnings are just reminders of work that needs to be done.
