### ISSUE TITLE
Saving Bunch to SDDS generates error

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#72]
When I generate a bunch on the Bunch tab and select "Save to File -> Elegant SDDS format," I get the following errors:

c:\users\mark harrison\documents\github\radtrack\radtrack\dcp\sdds.py:202: RuntimeWarning: tp_compare didn't return -1 or -2 for exception
  if sddsdata.SetColumn(self.index, i, self.columnData[i]) != 1:
Traceback (most recent call last):
  File "c:\users\mark harrison\documents\github\radtrack\radtrack\BunchTab.py", line 75, in <lambda>
    saveToSDDS.triggered.connect(lambda ignore : self.saveToSDDS())
  File "c:\users\mark harrison\documents\github\radtrack\radtrack\BunchTab.py", line 1431, in saveToSDDS
    mySDDS.save(sddsFileName)
  File "c:\users\mark harrison\documents\github\radtrack\radtrack\dcp\sdds.py", line 202, in save
    if sddsdata.SetColumn(self.index, i, self.columnData[i]) != 1:
TypeError: a float is required

The entire SDDS file generated is as follows:

SDDS1
&description contents="Copyright 2013-2014 by RadiaBeam Technologies. All rights reserved.", &end
&column name=x, units=m, type=float,  &end
&column name=xp, type=float,  &end
&column name=y, units=m, type=float,  &end
&column name=yp, type=float,  &end
&column name=t, units=s, type=float,  &end
&column name=p, units=m_ec, type=float,  &end
&data mode=ascii, &end

**Comment by bruhwile** [comment]
I fixed it by undoing a recent change to how column data is assembled before writing to SDDS.
Here's the new code (commented) with the restored code:
# The syntax commented out here does NOT work.
# The following, uncommented text does work.
#
#        mySDDS.columnData = [[list(tmp6[0,:])], [list(tmp6[1,:])],
#                             [list(tmp6[2,:])], [list(tmp6[3,:])],
#                             [list(tmp6[4,:])], [list(tmp6[5,:])]]
#
        mySDDS.columnData = [list(tmp6[0,:]), list(tmp6[1,:]),
                             list(tmp6[2,:]), list(tmp6[3,:]),
                             list(tmp6[4,:]), list(tmp6[5,:])]

**Comment by robnagler** [comment]
There must be a version issue. Paul and I both had the problem on Linux,
which the code change fixed -- hence the checkin.

I will look into what's happening on Windows vs Linux tomorrow.

Rob

**Comment by MZHarrison** [comment]
I just updated and the issue was fixed.

**Comment by MZHarrison** [comment]
SDDS output works on both windows and the vagrant VM. Closing.
