### ISSUE TITLE
integrate UI mockup into Elegant tab

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#78]

**Comment by bruhwile** [comment]
This is essentially done.
Paul demo'd the results for the weekly telecon, and it looks great.
It hasn't yet been tested on Windows.
Paul will push to Github this afternoon.

Note: Paul has been using and developing the Linux version of RadTrack, running inside a virtual machine on his Mac.

**Comment by bruhwile** [comment]
Looks like the push to Github just happened.
When I update and run on Win8, RadTrack fails with the following error:
***
D:\Python\x86\Anaconda\python.exe E:/pycharm/radiasoft/radtrack/radtrack/RbGlobal.py
Traceback (most recent call last):
  File "E:/pycharm/radiasoft/radtrack/radtrack/RbGlobal.py", line 20, in <module>
    from radtrack.RbEle import RbEle
  File "E:\pycharm\radiasoft\radtrack\radtrack\RbEle.py", line 14, in <module>
    import radtrack.RbGlobal
  File "E:\pycharm\radiasoft\radtrack\radtrack\RbGlobal.py", line 20, in <module>
    from radtrack.RbEle import RbEle
ImportError: cannot import name RbEle

Process finished with exit code 1
***

I see that RbEle imports RbGlobal and RbGlobal imports RbEle, which seems a bit circular...?

**Comment by MZHarrison** [comment]
I'm fixing this now.

**Comment by MZHarrison** [comment]
Fixed in commit 7e219e371f6349695b1fceb06fce0092bbe8df7b

**Comment by moellep** [comment]
I didn't include this in the commit message, but below is a summary of the
changes made to the elegant tab.

* Parameter input is shown as disabled until data entry is
  required. For example, the Simulate button is only enabled when all
  the required parameters have been entered. Also, the Beam Line combo
  box is disabled until a Beam Line Source is selected. When the
  simulation process is running, the parameter fields are disabled
  until the process has completed.

* Added "New beam bunch" and "New beam line" options to the Bunch
  Source and Beam Line Source combo boxes. Selecting the option will
  open a new tab of the appropriate type.

* After importing new Beam Line Source data, the Beam Line combo
  defaults to the last defined beam line.

* Imported Bunch Source and Beam Line Source files are shown in the
  combo box by their short file name. The full file path is maintained
  internally to the combo box in the Qt.UserData field.

* The simulation completion message depends on the exit/status code
  from the elegant process.

* The status menu has a context menu which is available after the
  simulation has completed which allows viewing the full
  stderr/stdout output or the summary output. The summary view is the
  default.

* Stdout and stderr lines are automatically processed as the elegant
  process runs, and any warnings and errors are automatically shown on
  the status summary field.

* Output files which originate in the lattice definition are labeled
  in the results as "<lattice field name>: <lattice field type>".

* Other files defined in the elegant command file use the SDDS
  description tag when displayed in the result list. If no description
  is present in the SDDS file, then the file name is used.

* The results context menu is dependent on the selected file type. LTE
  files show a link to the Bunch Transport tab. SDDS files will show
  links to the Visualization tabs. SDDS files which contain 6D columns
  will also show a link to the Bunch tabs.

* A busy indicator is shown when the simulation is running and hidden
  after the elegant process is finished.

* An abort button is available when the simulation is
  running. Selecting abort allows terminating the elegant process and
  starting a new simulation with different values.

Paul
