### ISSUE TITLE
RbUtility for SRW

### ISSUE THREAD

**Issue by qedseung** [radiasoft/radtrack#79]
Trying to use the method convertUnitsStringToNumber to strip away units and save just the number results in a ValueError:

conversionFactorStr = float(parseUnits('1' + oldUnit))/float(parseUnits('1' + newUnit))
ValueError: invalid literal for float()
raise ValueError('Cannot convert "' + oldUnit + '" to "' + newUnit + '".')

(maybe there are spurious characters?)

**Comment by MZHarrison** [comment]
Can you post a file that I can run that demonstrates the error?

You can paste it here: https://gist.github.com/

**Comment by qedseung** [comment]
I synced to the RadTrack repository so you should be able to run
RbSrwsingleA.py and it should demonstrate the error.

On Thu, Apr 9, 2015 at 5:26 PM, Mark Harrison <notifications@github.com>
wrote:

> Can you post a file that I can run that demonstrates the error?
>
> You can paste it here: https://gist.github.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/79#issuecomment-91387770>.
>



-- 
Radiabeam Technologies
1717Stewart St
Santa Monica, CA 90404
310-822-5845

**Comment by qedseung** [comment]
let me see if i can write something that demos it simpler

On Thu, Apr 9, 2015 at 5:32 PM, Steve Seung <seung@radiabeam.com> wrote:

> I synced to the RadTrack repository so you should be able to run
> RbSrwsingleA.py and it should demonstrate the error.
>
> On Thu, Apr 9, 2015 at 5:26 PM, Mark Harrison <notifications@github.com>
> wrote:
>
>> Can you post a file that I can run that demonstrates the error?
>>
>> You can paste it here: https://gist.github.com/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/radiasoft/radtrack/issues/79#issuecomment-91387770>.
>>
>
>
>
> --
> Radiabeam Technologies
> 1717Stewart St
> Santa Monica, CA 90404
> 310-822-5845
>



-- 
Radiabeam Technologies
1717Stewart St
Santa Monica, CA 90404
310-822-5845
