### ISSUE TITLE
misplacement of & in parsed *.lte files

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#80]
The Elegant *.lte files use "&" as a line continuation character. 
If this is in the middle of a string, Elegant won't accept the file.

For example: importing the external/elegant/beamlines/aps.lte 
will generate the following lte text:
>>
RF:  RFCA, VOLT=12e6, PHASE="180 5.35 12 / dasin -", FREQ="7e3 mev / beta.p &
           c_mks * 1104 / 1296 *"
<<
Instead, it should split the line outside of string values, or skip the line splitting entirely. 

Note that Elegant doesn't require 80 character lines.

(Problem identified by Paul M.)

**Comment by MZHarrison** [comment]
Fixed in commit ae2c8b93f83b171e0cad492304b464751a2e6db7. I would like to keep generated files word-wrapped so that they are easier to edit in a text editor should a user choose to do so.

I can be convinced otherwise.
