### ISSUE TITLE
inclusion of additional files from inside a *.lte file

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#82]
If an Elegant *.lte file refers to another input file, it needs to be copied into the project directory for the corresponding *.ele file to access it.

For example, external/elegant/beamlines/dtSweep.lte has a zwake entry which refers to the "knsl45.liwake.sdds" file.
       ZWAKE:  WAKE, INPUTFILE="knsl45.liwake.sdds", TCOLUMN="t", WCOLUMN="W", &
                       FACTOR="86 10 /", N_BINS=1024

Currently if Elegant is run from RadTrack with this file, it emits an error to STDERR, and then continues normally:
       Error: unable to open or read WAKE file knsl45.liwake.sdds

If the file doesn't exist, an error message should be shown instead of running the simulation. 

If possible, the input file should be copied into the project directory when the original .lte file is imported.

(This issue was identified by Paul M.)

**Comment by MZHarrison** [comment]
This code could use some testing since none of the example beam lines in the repository have associated files that actually exist in their folder.

**Comment by MZHarrison** [comment]
The bunch transport tab should now pop up an error if an Elegant element specifies a non-existent input file. (Commit bff038fc5b7c7f8db65f9a53fb28fc6555327472).
