### ISSUE TITLE
improve VM installation and update on MacOS

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#83]
Once the RadTrack VM has been installed the first time, future updates will be easy for the user to manage (some will be automatic). Only changes will be brought down to the desktop.

I know Rob has been working on this and initial code can be found in the new Github repositories:
   https://github.com/radiasoft/radtrack-updates 
   https://github.com/radiasoft/radtrack-installer

**Comment by bruhwile** [comment]
Should this issue be closed?

**Comment by robnagler** [comment]
I've documented. One person did the install himself after that update.

Rob
