### ISSUE TITLE
Testing framework implicitly uses Version 1 of QString

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#87]
With commit 9767e4559f374c71efc9987c45f9133d71204a6a, tests of RadTrack I had previously written have been integrated into the testing framework. However, these now fail with the error:

    E    ValueError: API 'QString' has already been set to version 1

Throughout RadTrack, we use version 2 (which is the same as the native Python string) using:

    import sip
    sip.setapi('QString', 2)

Somehow, our testing framework (py.test) is implicitly using `sip.setapi('QString', 1)`, causing `importExport_test.py`, `felCalc_test.py`, and `rpn_test.py` to fail.

**Comment by robnagler** [comment]
I'm getting a core dump on linux when I run the rpn_test.py with this error:

QWidget: Must construct a QApplication before a QPaintDevice

I don't see why PyQt should bomb this way, but it does. I'm not seeing the
QString error.

Don't have time debug this right now, but I'll put it in my list.

The "chdir" in the rpn_test.py needs to be more sophisticated and not have
a hardwired Windows path. Forward slashes work on Windows so we should use
them or configure the name or use os.path.join.

Rob

**Comment by robnagler** [comment]
rpn_test.py is not a py.test so it can't be run with "py.test". Simply
renaming the file to be something_test.py doesn't make it a proper py.test
file. There's not much required, but there needs to be a little bit of
structure. Here's a quick tutorial:

http://pytest.org/latest/getting-started.html#our-first-test-run

When you run "python rpn_test.py" it fails with the same core dump so this
has nothing to do with py.test.

Adding in this code helps:

from PyQt4 import QtGui
app = QtGui.QApplication(sys.argv)
myapp = RbBunchTransport()
myapp.show()

but still ends with this error:

  File "rpn_test.py", line 42, in <module>
    myapp = RbBunchTransport()
TypeError: 'module' object is not callable

I suspect that you really need to be in the Qt interpreter loop.

We need to separate out the business logic from the Qt so we can test the
code properly. Paul said he was looking into do Qt testing, which is fine,
but rpn_test.py for example doesn't need to import Qt to test the RPN
business logic.

Rob

**Comment by MZHarrison** [comment]
Commit 19d7c0f600b49b5df576fc17c60ca2d707706287 should clear a bunch of these errors up.

**Comment by MZHarrison** [comment]
Closing issue since this was due to my not understanding the testing framework.
