### ISSUE TITLE
add Elegant examples to the repository

### ISSUE THREAD

**Issue by bruhwile** [radiasoft/radtrack#88]
The repository includes several example lattice files and a few beam files. However, one cannot combine lattice files and beam files randomly and expect reasonable results.

The Elegant examples need to be included in the repository with their full context.

**Comment by robnagler** [comment]
Is there a programmatic way to detect dependencies? If not, can you give me
a list of relationships? It should be automatic which files go with which.
We can do this easily if you give us the mapping.

Rob

**Comment by bruhwile** [comment]
The algorithm at present is to:
   1) select a directory from the elegantExamples/ distribution
   2) use the files in that directory

I thought about just copying all these directories over into the
.../use_case/ directory of the repo, but thought maybe it should happen
incrementally. Also, I want to create "use case" Power Point files like
what Gerard did for his use case, so it's clear to a human what the use
case is about and what the resulting images should be.

We should move from Power Point to a wiki page, of course.

To get at the dependencies in a more algorithmic and automated fashion, we
have to look at all the examples to see if patterns emerge. In some cases,
like reference to a named file, it's obvious that the named file has to be
in the same directory as the other input files, so Elegant will find it.

At the moment, RadTrack will not support many of the Elegant capabilities
expressed in these examples. We'll have to generalize the Elegant tab
accordingly. A quick fix for the completely general case of some
complicated *.ele file would be take the specified file and modify it based
on input from the Elegant tab, as opposed to having the Elegant tab create
the file from scratch.

David
