### ISSUE TITLE
SRW multi particle does not work with Horizontal (and helical?) undulators

### ISSUE THREAD

**Issue by qedseung** [radiasoft/radtrack#89]
The multi particle version of SRW hangs when running with a horizontal/helical undulator

**Comment by qedseung** [comment]
Update allows for output from helical undulator simulations

**Comment by MZHarrison** [comment]
Is this issue still ongoing?

**Comment by bruhwile** [comment]
We've decided this is out of scope for the present project.
I'm closing the issue for now.
It can be reopened in the future.
