### ISSUE TITLE
Separate beam bunch generation from profile choice

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#91]
In BunchTab, the beam profile shape choice ("gaussian", etc.) and the generate bunch functions are combined in the QToolButton "Generate Bunch". These two functions should be separated into two controls: a dropdown menu (QComboBox) for the profile shape and a button to generate the bunch. This way, a default shape can be set in the menu, which will allow the saving of the tab even if the user never pushes the "Generate Bunch" button.

As it is now, if the user never presses "Generate Bunch", exportToFile (which is set to saveToSDDS) errors out when trying to access self.myBunch, which is only created by the generateBunchRT() function. This causes problems when saving multiple tabs in a project and when trying to run an Elegant simulation.

**Comment by bruhwile** [comment]
A default value of self.distributionFlag is set in the constructor of the BunchTab class.
So I don't understand the problem.

However, it's a good idea to separate specification of the distribution type from the act of creating the distribution. I agree that they never should have been coupled.

I've cleaned up the Bunch tab quite a bit, including this separation.

I won't close this ticket until I hear that the original problem has been solved.

**Comment by MZHarrison** [comment]
The changes you made did solve the problem. Now, if the user forgets to push Generate Beam, project saving and Elegant simulations can proceed without error.

I would suggest replacing the Distribution button (currently a QToolButton: self.distribType in radtrack/ui/BunchInterface.py) with a QComboBox so the user can see the current selection without having to open up the menu.
