### ISSUE TITLE
Adding beam lines in Bunch Transport tab does not update Elegant tab beam line choices

### ISSUE THREAD

**Issue by MZHarrison** [radiasoft/radtrack#93]
Steps to reproduce:

1. Create a beam line in the Bunch Transport tab.
2. Go to Elegant tab
3. Select Bunch Transport tab as source, created beam line is automatically selected
4. Go back to Bunch Transport tab, create new beam line
5. Go back to Elegant tab, note that the new beam line is not an available choice

See the User Test Video (Marcos.mov in Dropbox/RadTrack/20150504-User-Test/) at 17:45 for a demonstration.

**Comment by bruhwile** [comment]
The problem occurs with the bunch tab, also.
We need to develop a coherent strategy for how tab data is managed, saved
to file, etc.
This will be a good topic for the Monday telecon.

David

On Wed, May 6, 2015 at 6:31 PM, Mark Harrison <notifications@github.com>
wrote:

> Steps to reproduce:
>
>    1. Create a beam line in the Bunch Transport tab.
>    2. Go to Elegant tab
>    3. Select Bunch Transport tab as source
>    4. Go back to Bunch Transport tab, create new beam line
>    5. Go back to Elegant tab, note that the new beam line is not an
>    available choice
>
> See the User Test Video (Marcos.mov in
> Dropbox/RadTrack/20150504-User-Test/) at 17:45 for a demonstration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiasoft/radtrack/issues/93>.
>



-- 
David Bruhwiler
RadiaSoft LLC
+1 (720) 502-3928
